openapi: 3.0.3
info:
  title: Agreement Management Micro Service
  description: 'This is a sample server'
  version: 0.0.1
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  termsOfService: 'http://swagger.io/terms/'
  x-api-id: an x-api-id
  x-summary: an x-summary
servers:
  - url: https://gateway.interop.pdnd.dev/pdnd-interop-uservice-agreement-management/0.0.1
    description: This service is agreement manager
#security:
#  - bearerAuth: [ ]
tags:
  - name: agreement
    description: Everything about your Agreement
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /agreements:
    post:
      tags:
        - agreement
      summary: Add a new agreement
      operationId: addAgreement
      requestBody:
        description: A Agreement seed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgreementSeed'
        required: true
      responses:
        "200":
          description: Agreement created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agreement'
        "405":
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    get:
      tags:
        - agreement
      summary: Retrieve a list of agreement
      operationId: getAgreements
      parameters:
        - in: query
          name: producer_id
          schema:
            type: string
        - in: query
          name: consumer_id
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: string
            enum: [draft, active, suspended]
      responses:
        "200":
          description: A list of Agreement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agreements'
  /agreements/{agreement_id}:
    get:
      tags:
        - agreement
      summary: Get an agreement
      operationId: getAgreement
      parameters:
        - name: agreement_id
          in: path
          description: the agreement id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Agreement retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agreement'
        '404':
          description: Agreement not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    AgreementSeed:
      type: object
      required:
        - eservice_id
        - producer_id
        - consumer_id
      properties:
        eservice_id:
          type: string
          format: uuid
        producer_id:
          type: string
          format: uuid
        consumer_id:
          type: string
          format: uuid
    Agreement:
      type: object
      required:
        - id
        - eservice_id
        - producer_id
        - consumer_id
        - status
      properties:
        id:
          type: string
          format: uuid
        eservice_id:
          type: string
          format: uuid
        producer_id:
          type: string
          format: uuid
        consumer_id:
          type: string
          format: uuid
        status:
          type: string
          enum: ['active']
    Agreements:
      type: array
      items:
        $ref: '#/components/schemas/Agreement'
    Problem:
      properties:
        detail:
          description:
            A human readable explanation specific to this occurrence of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
        status:
          description:
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description:
            A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: '^[ -~]{0,64}$'
          type: string
      additionalProperties: false
      required:
        - status
        - title