/**
 * Agreement Management Micro Service
 * defines the persistence operations for the agreement
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.agreementmanagement.client.model

import java.util.UUID
import it.pagopa.pdnd.interop.uservice.agreementmanagement.client.invoker.ApiModel

case class Agreement (
  id: UUID,
  eserviceId: UUID,
  descriptorId: UUID,
  producerId: UUID,
  consumerId: UUID,
  status: AgreementEnums.Status,
  /* set of the verified attributes belonging to this agreement, if any. */
  verifiedAttributes: Seq[VerifiedAttribute],
  suspendedByConsumer: Option[Boolean] = None,
  suspendedByProducer: Option[Boolean] = None
) extends ApiModel

object AgreementEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Active = Value("active")
    val Pending = Value("pending")
    val Suspended = Value("suspended")
    val Inactive = Value("inactive")
  }

}
