/** Agreement Management Micro Service
  * defines the persistence operations for the agreement
  *
  * The version of the OpenAPI document: {{version}}
  * Contact: support@example.com
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package it.pagopa.pdnd.interop.uservice.agreementmanagement.client.model

import java.util.UUID

import it.pagopa.pdnd.interop.uservice.agreementmanagement.client.invoker.ApiModel

case class AgreementSeed(
  eserviceId: UUID,
  descriptorId: UUID,
  producerId: UUID,
  consumerId: UUID,
  /* set of the verified attributes belonging to this agreement, if any. */
  verifiedAttributes: Seq[VerifiedAttributeSeed]
) extends ApiModel
