/**
 * Agreement Management Micro Service
 * defines the persistence operations for the agreement
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.pdnd.interop.uservice.agreementmanagement.client.model

import it.pagopa.pdnd.interop.uservice.agreementmanagement.client.invoker.ApiModel

case class StatusChangeDetails (
  changedBy: Option[StatusChangeDetailsEnums.ChangedBy] = None
) extends ApiModel

object StatusChangeDetailsEnums {

  type ChangedBy = ChangedBy.Value
  object ChangedBy extends Enumeration {
    val Producer = Value("producer")
    val Consumer = Value("consumer")
  }

}
